version: '3.8'

services:
    reverse-proxy:
        image: nginx:1.17.10
        depends_on:
            - strapi
            - gatsby
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    strapi:
        build:
            context: ./strapi
            dockerfile: Dockerfile.prod
        volumes:
            - ./strapi/src/:/usr/src/strapi/src
        ports:
            - '1337:1337'
        depends_on:
            - postgres

    gatsby:
        stdin_open: true
        tty: true
        build:
            context: ./gatsby
            dockerfile: Dockerfile.prod
        volumes:
            - ./gatsby/src/:/usr/src/gatsby/src
            - ./gatsby/gatsby-config.js:/usr/src/gatsby/gatsby-config.js
            - ./gatsby/cronjob.js:/usr/src/gatsby/cronjob.js
        environment:
            - GATSBY_WEBPACK_PUBLICPATH=/
        ports:
            - 3000:3000

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: strapi
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    postgres:
