version: '3.8'

services:
    strapi:
        build:
            context: ./strapi
            dockerfile: Dockerfile.dev
        volumes:
            - ./strapi/src/:/usr/src/strapi/src
        environment:
            DATABASE_CLIENT: postgres
            DATABASE_NAME: strapi
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        ports:
            - '1337:1337'
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: strapi
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
        volumes:
            - ./data:/var/lib/postgresql/data

volumes:
    postgres:
