FROM node:16-alpine

# Server path
WORKDIR /usr/src/strapi

# Copy package.json that holds our configuration
COPY ./package.json .

# Install local dependencies
RUN yarn install && yarn cache clean && yarn build

#
COPY . .

#
EXPOSE 1337

# Build and run strapi
CMD yarn build && yarn start