FROM node:16-alpine

# Server path
WORKDIR /usr/src/strapi

# Copy package.json that holds our configuration
COPY ./package.json .

# Install local dependencies
RUN yarn install && yarn cache clean

#
COPY . .

#
EXPOSE 1337

# Run strapi in development mode
CMD NODE_ENV=development yarn develop