name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2
            - name: Add .env file
              run: |
                  touch ./strapi/.env
                  echo APP_KEYS=${{ secrets.APP_KEYS }} >> ./strapi/.env
                  echo API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} >> ./strapi/.env
                  echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} >> ./strapi/.env
            - name: Build the Docker image
              run: docker-compose -f docker-compose.prod.yml up --force-recreate --build -d && docker image prune -f
