name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker-compose -f docker-compose.prod.yml up --force-recreate --build -d && docker image prune -f
